name: Github Pages Deploy
on:
  release:
    types: [published]
      
jobs:
  uploadFTP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftpserver }}
          username: ${{ secrets.ftpuser }}
          password: ${{ secrets.ftppassword }}
