name: Github Pages Deploy
on:
  release:
    types: [published]
      
jobs:
  uploadFTP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'gh-pages'
      - name: FTP upload
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.ftpserver }}
          user: ${{ secrets.ftpusername }}
          password: ${{ secrets.ftppassword }}
          options: --insecure --all
