name: Github Ftp actions
on:
  workflow_dispatch:
      
jobs:
  uploadFTP:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'gh-pages'
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftpes://ftp.environmentalenforcementwatch.org"
        user: ${{ secrets.ftpuser }}
        password: ${{ secrets.ftppassword }}
        options: --auto-init --force --verbose --insecure --all
